language: node_js
node_js:
    - "10"
    - "8"
python:
    - "3.6"
before_install:
    - sudo apt-get -y install python3-pip python-dev
    - pip3 install --user pyro4
    - python3 -c "import Pyro4"
